version: "3"
services:
  consul:
    image: consul
    container_name: consul
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - TZ=Asia/Shanghai
#    command: ["agent" ,"-dev", "-ui","-config-dir=../consul/config", "-client=0.0.0.0"]
    command: ["agent" ,"-dev", "-ui", "-client=0.0.0.0"]
#    volumes:
#      - ../consul/config:/consul/config
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_XMN=128m
      - TZ=Asia/Shanghai
    ports:
      - 8848:8848
      - 9848:9848
  jaeger:
    image: jaegertracing/all-in-one:1.47
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
      - TZ=Asia/Shanghai
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - TZ=Asia/Shanghai
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Shanghai
  kong-database:
    image: postgres:12
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"

  kong-migrations:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=192.168.2.6
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-database

  kong:
    image: kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=192.168.2.6
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_LISTEN=0.0.0.0:8000, 0.0.0.0:8443 ssl
      - KONG_DNS_RESOLVER=192.168.2.6:8600,114.114.114.114
    restart: on-failure
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8004"
      - "8004:8004"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
    links:
      - kong-database:kong-database
    depends_on:
      - kong-migrations

  konga:
    image: pantsel/konga
    ports:
      - 1337:1337
    links:
      - kong:kong
    container_name: konga
    environment:
      - NODE_ENV=production
volumes:
  db-data-kong-postgres:


