global:
  scrape_interval: 15s
  external_labels:
    monitor: 'go-zero-admin-monitor'
scrape_configs:
  - job_name: 'base'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.2.6:9002']