// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"github.com/google/wire"

	"github.com/laoningmeng/go-zero-admin/services/admin/admin"
	"github.com/laoningmeng/go-zero-admin/services/admin/internal/logic"
	"github.com/laoningmeng/go-zero-admin/services/admin/internal/svc"
)
var ProviderSet = wire.NewSet(NewAdminServer)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	u *logic.UserLogic
	r *logic.RoleLogic
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext, userLogic *logic.UserLogic, roleLogic *logic.RoleLogic) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
		u: userLogic,
		r: roleLogic,
	}
}